{
  "name": "test-module",
  "version": "1.0-SNAPSHOT",
  "authors": ["Programm"],

  "module-package": "com.programm.projects.scripty.module.test",
  "module-files": [
    "TestModule",
    "func/DivByZeroNode",
    "func/DivisionByZeroException",
    "func/FContext",
    "func/FFunction",
    "func/FNode",
    "func/Function",
    "func/FunctionAnalyzer",
    "func/FunctionNode",
    "func/FunctionParseException",
    "func/FunctionParser",
    "func/IFunction",
    "func/OperationNode",
    "func/StringUtils",
    "func/ValueNode",
    "func/VarNode"
  ],
  "module-entry": "TestModule",

  "depends": {}
}